= Neosemantics Graph App
:page-pagination:

The *Neosemantics Graph App* is an extension of link:/developer/neo4j-desktop[Neo4j Desktop] that guides you through the process of importing and exporting data with Neosemantics.

After guiding you through the installation instructions, the Graph App

== How to Install

The Neosemantics Graph App is available to install from the link:https://install.graphapp.io[Graph App Gallery^] or by clicking the button below.

link:neo4j-desktop://graphapps/install?url=https://registry.npmjs.org/@graphapps/neosemantics[Install Neosemantics Graph App in Neo4j Desktop^, role="button feature-box_button"]

== Launching the Graph App

Once installed, you can open the Neosemantics app by clicking the Open icon next to the Graph App in the *Graph Applications* pane found on the left hand side of the Neo4j Desktop UI.
You can also launch the Graph App from the Action bar by clicking the magnifying glass in the top right hand corner or using the keyboard shortcut: `Ctrl+K` on Windows, `Cmd+K` on Mac.
Once the Action bar has opened, you can start to type _Neosemantics_ and select **Open Neosemantics** from the list of suggestions.


== Using the Graph App

=== Installing The Plugin

video::neosemantics-first-start.mp4[]
If Neosemantics hasn't already been installed on your current active Graph, you will be guided through the xref:installation.adoc[Installation] process.

=== Generating Cypher Statements

video::neosemantics-generate-query.mp4[]
The Graph App will then display a number of forms that are designed to get you familiar with the functionality offered by Neosemantics.
As each form builds up a Cypher statement which you can either run by clicking the button at the bottom of each form or by copying and pasting the query into <<NEO4J_BROWSER>> or <<CYPHER_SHELL>>.


== Feedback

If you have any feedback on the Neosemantics Graph App, let us know through the feedback form at the bottom of each page or on the link:https://community.neo4j.com[Neo4j Community Forum^].

[discrete.glossary]
== Glossary

[glossary]
[[NEO4J_BROWSER]]Neo4j Browser:: Neo4j is a tool for querying and visualising data held in Neo4j.  If you have an instance of Neo4j Running, you can access Neo4j Browser by navigating to port `7474`, for example: link:http://localhost:7474/[http://localhost:7474/^]
+
link:/developer/neo4j-browser[Read More^]

[[CYPHER_SHELL]]Cypher Shell:: Cypher Shell is a command line tool for querying Neo4j.  You can find `cypher-shell` in the `bin/` folder of your Neo4j Installation
+
link:https://neo4j.com/docs/operations-manual/current/tools/cypher-shell/[Read More^]
