= Installing neosemantics
:page-pagination:


You can either download a prebuilt `.jar` from the https://github.com/jbarrasa/neosemantics/releases[releases area] or <<Building from source, build it from the source>>.
If you prefer to build, check the <<Building from Source, note below>>.


== Standalone Instance

Once you have obtained the `.jar` file for your version of Neo4j, you should copy it into the `plugins/` folder within the <<NEO4J_HOME>> directory of your Neo4j instance.
If you have not installed any plugins, this folder will contain a `README.txt` file.

[source,shell]
$ ls plugins
README.txt  neosemantics-4.0.0.1.jar

To enable the xref:getting-started:export[Export HTTP endpoint] you will also need to include following line in your `<<NEO4J_HOME>>/conf/neo4j.conf` configuration file:

[source,conf]
----
dbms.unmanaged_extension_classes=n10s.endpoint=/rdf
----


Once you have installed the plugin, you will need to restart the Neo4j instance before the plugin become available.

[source,shell]
$ bin/neo4j restart
Starting Neo4j.
Started neo4j (pid XXXXX). It is available at http://localhost:7474/
There may be a short delay until the server is ready.


== Causal Cluster

To install Neosemantics on to a <<CausalCluster>>, you should follow the installation instructions above on each cluster member.
The plugin will only be available on each individual instance once it has been restarted.


== Neo4j Desktop

1. Click the _three dot_ menu to the top left of the card of the database that you would like to install the plugin to
2. Click on the **Manage** icon
3. Click the downwards arrow next to the **Open Folder** button and click **Plugins**
4. Move the `.jar` file into the resulting window
5. Click the **Restart** icon to restart the database, or click the **Play** button to start the database.

== Docker

Neosemantics can be installed on a link:/developer/docker-run-neo4j/[Neo4j Docker^] instance by providing adding `n10s` to the `NEO4JLABS_PLUGINS` environment variable:

[source]
docker run \
    --name testneo4j \
    -p7474:7474 -p7687:7687 \
    -d \
    -v $HOME/neo4j/data:/data \
    -v $HOME/neo4j/logs:/logs \
    -v $HOME/neo4j/import:/var/lib/neo4j/import \
    -v $HOME/neo4j/plugins:/plugins \
    --env NEO4JLABS_PLUGINS='["apoc", "n10s"]' \
    --env NEO4J_AUTH=neo4j/test \
    neo4j:latest

link:/developer/docker-run-neo4j/[More information of running Neo4j with Docker^,role=more information]

== Verifying the Installation

To verify that the plugin has been installed, you can run the following Cypher query to list the procedures registered on the Neo4j instance.
This query should return a number of procedures where the name begins with `n10s`.

[source,cypher]
call dbms.procedures()



You can check that the HTTP endpoints have been mounted by running a GET request to the `/rdf/ping` endpoint.

[source]
----
:GET http://localhost:7474/rdf/ping
----

The previous command assumes you're running neo4j on your local machine, replace `localhost` with the host name if that is not the case.



== Building from Source

To build the neosemantic plugin from source, link:https://github.com/jbarrasa/neosemantics[Clone the neosemantics repository^] and run the  `mvn clean package` command.  This will produce two `.jar` files:

1. **`neosemantics-[...].jar`**: This jar bundles all the dependencies.
2. **`original-neosemantics-[...].jar`**: This jar is just the neosemantics bit. So go this way if you want to keep the third party jars separate. In this case you will have to add all third party dependencies (look at the pom.xml).



[discrete.glossary]
== Glossary

[glossary]
[[NEO4J_HOME]]$NEO4J_HOME:: The directory in which you have installed Neo4j.  This will contain a `bin/` folder which holds the `neo4j` executable, plus conf, data and plugins.
+
For more information, see the link:/ops-manual[Operations Manual^]
[[APOC]]APOC:: xref:apoc[APOC] is a library of procedures and functions that make your life as a Neo4j user easier.
[[CausalCluster]]Causal Cluster:: A highly available cluster of Neo4j servers