site:
  title: Neo4j Training

content:
  sources:
  - url: https://github.com/neo4j-contrib/training-v3.git
    branches: 'master'
    start_paths:
    - 'modules/home'
    - 'modules/4.0-intro-neo4j'
    - 'modules/4.0-overview'
    - 'modules/4.0-querying'
    - 'modules/4.0-updating'
    - 'modules/4.0-best-practices'
    - 'modules/4.0-importing-data'
    - 'modules/graph-data-modeling'
    - 'modules/4.0-implementing-graph-data-models'
    - 'modules/graphql-apis'
    - 'modules/4.0-neo4j-admin'
    - 'modules/4.0-cypher-query-tuning'
    - 'modules/4.0-intro-graph-algos'
    - 'modules/gds-data-science'
    - 'modules/gds-applied-algos'
    - 'modules/online-training-v2'
    - 'modules/neo4j-administration'
    # not yet ready - next in queue...
    #- 'modules/???'

output:
  dir: ./build/site/graphacademy

ui:
  bundle:
    url: https://d12wh7zj8x3amw.cloudfront.net/build/ui-bundle-latest.zip
    snapshot: true

urls:
  html_extension_style: indexify

asciidoc:
  extensions:
  - ./extensions/remote-include/remote-include-processor
  - ./extensions/macros/macros
  attributes:
    experimental: ''
    page-cdn: /static/assets
    page-component: training
    page-theme: training
    page-canonical-root: /graphacademy
    page-breadcrumbs:
      - name: Neo4j Training
        url: /graphacademy/online-training
    page-mixpanel: 4bfb2414ab973c741b6f067bf06d5575
antora:
  extensions:
    - '@neo4j-documentation/antora-training-extension'

