= Graph Database Developer Introduction, Training and Docs
:page-layout: labs


[.developer-intro]
== `(Neo4j)-[:LOVES]-(Developers)`

World's leading graph database, with native graph storage and processing.

Property graph model and Cypher query language makes it easy to understand.

**Fast. Natural. Fun.**



[.developer-stats]
link:https://neo4j.meetup.com[Meetup Group Members^]:: 47k
link:https://github.com/neo4j/neo4j[Commits to the Neo4j Core^]:: 46k
link:https://neo4j.com/graphacademy/[People have taken the neo4j training^]: 61K
link:https://neo4j.com/download/[Downloads^]: 2.5M
link:https://twitter.com/neo4j[Tweets per year^]: 100K

[.test-drive]
== Test-Drive Neo4j with Cypher

=== Social

==== Friends of Friends

Find all of Joe's second-degree friends

[source,cypher]
MATCH
  (person:Person)-[:KNOWS]-(friend:Person)-[:KNOWS]-
  (foaf:Person)
WHERE
  person.name = "Joe"
  AND NOT (person)-[:KNOWS]-(foaf)
RETURN
  foaf

Joe knows Sally, and Sally knows Anna. Bob is excluded from the result because, in addition to being a 2nd-degree friend through Sally, he's also a first-degree friend.

==== Common Friends

Find friends in common between Joe and Sally

[source,cypher]
MATCH
  (user:Person)-[:KNOWS]-(friend)-
    [:KNOWS]-(foaf:Person)
WHERE
  user.name = "Joe" AND foaf.name = "Sally"
RETURN
  friend.name AS friend

Joe and Sally both know Bob.


==== Connecting Paths

Connecting Paths
Find all paths, up to 6 degrees, between Joe and Billy

[source,cypher]
MATCH
  path = shortestPath(
    (p1:Person)-[:KNOWS*..6]-(p2:Person)
  )
WHERE
  p1.name = "Joe" AND p2.name = "Billy"
RETURN
  path

There's only one shortest path between Joe and Billy in this dataset, so that path is returned.

[source,cypher]

=== Network Management

==== Impact Analysis
Find all services that depend on Server 1. These would be impacted by an outage of that server.

[source,cypher]
MATCH
  (n:Service)<-[:DEPENDS_ON*]-(dependent:Service)
WHERE
  n.name = "Server 1"
RETURN
  dependent

Only Webserver VM depends on Server 1. Because we're looking at variable length paths of DEPENDS_ON relationships, we're also able to determine that Public Website would be impacted by an outage of Server 1.

==== Dependency Analysis

Find all services which the Public Website depends on to be operational.

[source,cypher]
MATCH
  (n:Service)-[:DEPENDS_ON*]->(downstream:Service)
WHERE
  n.name = "Public Website"
RETURN
  downstream

The Public Website depends on the Database VM and the Webserver VM, which each depend on other services.

==== Statistics
Find the most depended-upon component

[source,cypher]
MATCH
  (svc:Service)<-[:DEPENDS_ON*]-(dependent:Service)
RETURN
  svc,
  count(DISTINCT dependent) AS dependents
ORDER BY
  dependents DESC
LIMIT 1

As is the case in many data centers, the SAN is the most depended upon component. All six other services directly or indirectly depend on it.

=== Fraud Detection

==== Transitive Closure
Given suspicions about Hank, find related information to investigate.

[source,cypher]
MATCH
  (n:Person)-[*]-(o)
WHERE
  n.name = "Hank"
RETURN
  o

Hank shares an account with Abby. Abby shares a SSN with Sophie and Max. Given that we suspect Hank may be involved in fraudulent activity, we can flag the Cayman account, Sophie, and Abby as possible fraudulent entities.


==== Investigation Targeting
Fraud rings often share fraudulent identifying information. Any person with connections to more than two entities in the graph are suspicious. Find large cliques to investigate further.

[source,cypher]
MATCH
  (n:Person)-[*]-(o)
WITH
  n,
  count(DISTINCT o) AS size
WHERE
  size > 2
RETURN
  n

Sophie, Max and Abby all share a SSN, which is suspicious. Hank is also suspicious because he is sharing an account with Abby.


==== Fast Insights
Given that we've identified SSN 993-63-2634 as suspcious, find all associated accounts.

[source,cypher]
MATCH
  (ssn:SSN)<-[:HAS_SSN]-(:Person)-
  [:HAS_ACCOUNT]->(acct:Account)
WHERE
  ssn.number = 993632634
RETURN
  acct

We see that the Cayman account #863 is the only account where a Person using this SSN owns the account.


== Intro to Graph Databases

* Video 1
* Video 2
* Video 3


== Training and Certification

=== Online Training
Get started quickly with Neo4j by taking free online training classes.

=== Classroom Training
Offered locally in over a dozen cities around the globe.

=== Certification
Become a Neo4j Certified Professional to validate and promote your skills.



== Why Neo4j


=== Whiteboard Friendly
Model your connected data as it exists in the real-world — not as tables of columns and rows.

=== Global Community
Support for popular languages & frameworks. Learn Neo4j in different ways from our resources!

=== Native Graph Performance
Optimized graph storage and processing with the expressive Cypher query language.


== What It's Made of

=== FLEXIBLE SCHEMA

=== ACID

=== CLUSTERING FOR AVAILABILITY AND PERFORMANCE

=== POWERFUL CYPHER QUERY LANGUAGE

=== NEO4J BROWSER

=== DRIVERS FOR POPULAR LANGUAGES AND FRAMEWORKS

=== DATA IMPORT

=== CLOUD-READY


== Featured Community Members


== Upcoming Events Near You

== Featured Videos

== Online Meetup

== GraphGist Projects

